
(function(global){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct=x=>Number.isFinite(Number(x))?(Number(x)*100).toFixed(Number(x)<0.02?2:1)+'%':'—';
  const short=(s,n=180)=>{s=String(s??'');return s.length>n?s.slice(0,n)+'…':s;};
  const colors=['#2563eb','#16a34a','#dc2626','#9333ea','#ea580c','#0891b2','#ca8a04','#be123c'];
  const typeLabel={formula:'方劑',pattern:'證型',disease:'病證',diagnostic_feature:'症狀／診斷線索',herb:'藥物',wenbing_state:'溫病辨證狀態',knowledge_item:'考點',classic_clause:'條文'};
  const relLabel={formula_contains_herb:'組成含藥',has_component:'組成',herb_component_of_formula:'組成於方',formula_treats_pattern:'治療證型',pattern_uses_formula:'證型用方',treats_pattern:'治療',uses_formula:'使用方劑',disease_uses_formula:'病證用方',disease_has_pattern:'病證包含證型',pattern_belongs_to_disease:'隸屬病證',has_pattern:'包含證型',k3_has_pattern:'包含證型',symptom_supports_pattern:'支持證型',supports_pattern:'支持證型',supports:'支持',formula_has_symptom_hint:'方證線索',k3_has_symptom:'症狀線索',wenbing_state_has_symptom:'溫病狀態症狀',wenbing_state_uses_formula:'溫病狀態用方',formula_treats_wenbing_state:'治療溫病狀態',cooccurs_in_official_exam_question:'正式題共現',section_contains_entity:'章節包含',classic_clause_uses_formula:'條文用方',formula_has_classic_clause:'相關條文',classic_clause_mentions_symptom:'條文症狀',common_syndrome_uses_formula:'常見證型用方',formula_treats_common_syndrome_variant:'治療常見證型'};
  function polar(cx,cy,r,angle){const a=(angle-90)*Math.PI/180; return {x:cx+r*Math.cos(a), y:cy+r*Math.sin(a)};}
  function arcPath(cx,cy,r,start,end){const s=polar(cx,cy,r,end), e=polar(cx,cy,r,start); const large=end-start<=180?0:1; return `M ${cx} ${cy} L ${s.x.toFixed(3)} ${s.y.toFixed(3)} A ${r} ${r} 0 ${large} 0 ${e.x.toFixed(3)} ${e.y.toFixed(3)} Z`;}
  function chips(arr,limit=10){return (arr||[]).slice(0,limit).map(x=>`<span class="chip">${esc(x)}</span>`).join('');}
  class LearningPage{
    constructor(root,payload){this.root=typeof root==='string'?document.querySelector(root):root;this.p=payload||{};this.mode='books';this.book=(this.p.book_summaries||[])[0]?.book_id||'shanghan';this.formula=(this.p.formula_cards||[])[0]?.formula_id||'';this.pd=(this.p.pattern_disease_cards||[])[0]?.entity_id||'';this.cmpA='';this.cmpB='';this.recall=[];this.loadRecall();this.initCompareDefaults();}
    loadRecall(){try{this.recall=JSON.parse(localStorage.getItem('clinical1_learning_recall_v5')||'[]')}catch(e){this.recall=[]}}
    saveRecall(){localStorage.setItem('clinical1_learning_recall_v5',JSON.stringify(this.recall.slice(-500)));}
    initCompareDefaults(){const ci=this.p.comparison_index||{};const nodes=ci.nodes||[];const find=(name)=>nodes.find(n=>n.name===name)||nodes.find(n=>String(n.name||'').includes(name));this.cmpA=(find(ci.default_pair?.a_name||'桂枝湯')||nodes[0]||{}).id||'';this.cmpB=(find(ci.default_pair?.b_name||'麻黃湯')||nodes[1]||{}).id||'';}
    render(){if(!this.root)return;const m=this.p.metadata||{};const scope=m.friendly_scope_label||m.scope_rule||'正式大考題';this.root.innerHTML=`<div class="learning-page-v5"><div class="source-head learning-head"><h2>學習頁 v5.6.4：五本書學習入口、方證要點與考生化鑑別</h2><p>資料頁、知識樹、關係圖、方劑工具與考題熱點完整保留；本頁只作考場內化入口。五本書按 Bula／資料庫既有書目分流，僅作學習導航，不再宣稱為精確出題分布。</p><div class="learning-scope-note"><b>題庫範圍：</b>${esc(scope)}｜<b>正式題索引：</b>${Number(m.official_question_count||0).toLocaleString()} 題｜<b>分類狀態：</b>書目導向學習分流，非精確分布</div></div><div class="toolbar learning-mode-tabs">${[['books','五本書題型'],['spec','v5.0b 規格'],['formula','v5.1 方劑學習卡'],['pattern','v5.2 病證／證型卡'],['chapter','v5.3 章節路徑'],['compare','v5.5 任兩節點鑑別'],['recall_hidden','主動回憶暫隱藏']].map(x=>`<button class="btn ${this.mode===x[0]?'primary':''}" data-learn-mode="${x[0]}">${x[1]}</button>`).join('')}</div><div id="learningBody"></div></div>`;this.bind();this.renderBody();}
    bind(){this.root.onclick=e=>{const m=e.target.closest('[data-learn-mode]');if(m){this.mode=m.dataset.learnMode;this.render();return;}const b=e.target.closest('[data-learn-book]');if(b){this.book=b.dataset.learnBook;this.renderBody();return;}const f=e.target.closest('[data-learn-formula]');if(f){this.formula=f.dataset.learnFormula;this.renderBody();return;}const p=e.target.closest('[data-learn-pd]');if(p){this.pd=p.dataset.learnPd;this.renderBody();return;}const c=e.target.closest('[data-compare-pick]');if(c){this[c.dataset.compareSide==='b'?'cmpB':'cmpA']=c.dataset.comparePick;this.renderCompare();return;}const add=e.target.closest('[data-add-recall]');if(add){this.addRecall(add.dataset.addRecall,add.dataset.kind||'review');return;}const done=e.target.closest('[data-recall-done]');if(done){this.markRecall(done.dataset.recallDone,true);return;}const miss=e.target.closest('[data-recall-miss]');if(miss){this.markRecall(miss.dataset.recallMiss,false);return;}};this.root.oninput=e=>{if(e.target.id==='learnFormulaSearch')this.renderFormulaList(e.target.value); if(e.target.id==='learnPdSearch')this.renderPdList(e.target.value); if(e.target.id==='cmpSearchA')this.renderCompareList('a',e.target.value); if(e.target.id==='cmpSearchB')this.renderCompareList('b',e.target.value);};}
    body(){return this.root.querySelector('#learningBody')}
    renderBody(){if(this.mode==='books')return this.renderBooks(); if(this.mode==='spec')return this.renderSpec(); if(this.mode==='formula')return this.renderFormula(); if(this.mode==='pattern')return this.renderPD(); if(this.mode==='chapter')return this.renderChapter(); if(this.mode==='compare')return this.renderCompare(); if(this.mode==='recall')return this.renderRecall(); if(this.mode==='recall_hidden')return this.renderRecallHidden();}
    renderBooks(){
      const host=this.body();const books=this.p.book_summaries||[];const cur=books.find(x=>x.book_id===this.book)||books[0]||{};
      host.innerHTML=`<div class="card learning-book-note"><h3>五本書學習入口</h3><p>這裡按五本書整理題型與學習策略；題數僅代表目前正式題索引被分到該書的數量，屬學習導航，不作為嚴格出題比例或分布結論。</p><div class="learning-book-compact">${books.map((d,i)=>`<button class="legend-row compact ${d.book_id===this.book?'active':''}" data-learn-book="${esc(d.book_id)}"><span class="color-dot" style="background:${colors[i%colors.length]}"></span><b>${esc(d.label)}</b><span>${esc(d.count)} 題</span></button>`).join('')}</div></div><div class="learning-layout compact-learning-layout"><section class="card"><h3>${esc(cur.label||'')}：常見出題任務</h3>${this.renderTaskRows(cur.task_rows||[])}<p class="muted">任務分類是規則式初分，用來決定學習頁優先欄位；正式背誦仍需回到條文、方證與正式題。</p></section><section class="card"><h3>呈現方式與認知層次</h3><h4>題目呈現方式</h4><div class="chip-list">${(cur.format_counts||[]).map(x=>`<span class="chip">${esc(x.label)} ${esc(x.count)}</span>`).join('')}</div><h4>認知層次</h4><div class="chip-list">${(cur.cognitive_counts||[]).map(x=>`<span class="chip">${esc(x.label)} ${esc(x.count)}</span>`).join('')}</div><button class="btn primary" data-quiz-scope='${esc(JSON.stringify({learning_book_id:cur.book_id,tree_label:cur.label,keywords:[cur.label],layer:'official_exam'}))}'>以本書學習範圍出題</button></section></div>`;
    }
    renderTaskRows(rows){return `<div class="learning-task-list">${rows.map((r,i)=>`<details class="learn-task" ${i<2?'open':''}><summary><b>${esc(r.label)}</b><span>${r.count} 題｜${pct(r.ratio)}</span><em>${esc(r.learning_priority||'')}</em></summary><div class="learning-example-list">${(r.examples||[]).map(q=>this.qCard(q)).join('')}</div></details>`).join('')}</div>`}
    renderSpec(){const fp=this.p.field_priority||{};this.body().innerHTML=`<div class="card"><h3>v5.0b：學習頁規格書與欄位優先級</h3><p>主卡只放 A/B/C 級資料；D 級自動抽取只作候選，E 級不得放主卡。目的不是再做第二個大腦，而是把資料轉成考場可提取能力。</p><div class="grid learning-mini-stats">${Object.entries(fp).map(([k,arr])=>`<div class="card soft"><h4>${esc(k)}</h4><ol>${arr.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>`).join('')}</div><h4>資料可信度</h4>${(this.p.source_trust_schema||[]).map(x=>`<div class="trust-row trust-${esc(x.level)}"><b>${esc(x.level)}｜${esc(x.label)}</b><div>${esc(x.allowed_use)}</div></div>`).join('')}</div>`}
    formulaCards(){return this.p.formula_cards||[]}
    selectedFormula(){return this.formulaCards().find(x=>x.formula_id===this.formula)||this.formulaCards()[0]||{}}
    renderFormulaList(q=''){const host=this.root.querySelector('#learnFormulaList');if(!host)return; q=String(q||'').trim();const rows=this.formulaCards().filter(x=>!q||String(x.name).includes(q)||String(x.formula_id).includes(q)).slice(0,120);host.innerHTML=rows.map(x=>`<button class="type-list-row ${x.formula_id===this.formula?'active':''}" data-learn-formula="${esc(x.formula_id)}"><b>${esc(x.name)}</b><span>${x.rank?'#'+x.rank:'有題'}</span></button>`).join('')||'<p class="muted">找不到方劑。</p>'}
    variantDeltaText(v){
      const added=(v.added_herbs_computed_v4_6||v.added_herbs||[]).filter(Boolean);
      const removed=(v.removed_herbs_computed_v4_6||v.removed_herbs||[]).filter(Boolean);
      const changed=(v.dose_or_processing_changes_v4_6||[]).map(c=>{
        if(typeof c==='string')return c;
        const name=c.herb_name||c.name||''; const b=c.base_dose||c.base_processing||'原方'; const nv=c.variant_dose||c.variant_processing||'變方';
        return name?`${name}（${b}→${nv}）`:'';
      }).filter(Boolean);
      const rows=[]; if(added.length)rows.push('加：'+added.join('、')); if(removed.length)rows.push('去：'+removed.join('、')); if(changed.length)rows.push('調整：'+changed.join('、'));
      return rows.join('；') || v.variant_display_delta || v.delta_summary_v4_6 || '差異待核對';
    }
    renderFormulaIndications(ind){
      if(!ind)return '<p class="muted">尚未建立方證要點與條文索引。</p>';
      const chips=(arr,limit=12)=>(arr||[]).slice(0,limit).map(x=>`<span class="chip">${esc(x.name||x)}</span>`).join('');
      const clause=(c)=>`<article class="learning-clause-card"><div><b>${esc(c.clause_name||('條文 '+(c.clause_no||'')))}</b><span class="badge">${esc(c.source_trust_level||'A')}</span><span class="chip">${esc(c.source_book||'')}</span></div><p>${esc(c.text||'')}</p>${(c.symptom_terms||[]).length?`<div class="chip-list">${(c.symptom_terms||[]).slice(0,12).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div>`:''}</article>`;
      return `<section class="card soft formula-indication-card"><h4>方證要點／適用症狀</h4><p class="muted">主卡優先顯示原文條文與明確表格；「正式題常見線索」只代表考題共現，不等於臨床適應症。</p>${(ind.summary||[]).map(x=>`<p class="big-line">${esc(x)}</p>`).join('')}<h5>適用證候／病證候選</h5><div class="chip-list">${chips(ind.target_patterns_or_diseases)||'<span class="muted">尚未建立高可信證候連結。</span>'}</div><h5>正式題常見症狀線索</h5><div class="chip-list">${(ind.symptom_hints||[]).slice(0,14).map(x=>`<span class="chip">${esc(x.name)}${x.official_cooccurrence_count?`｜${esc(x.official_cooccurrence_count)}題`:''}</span>`).join('')||'<span class="muted">尚無正式題線索。</span>'}</div><h5>對應條文</h5><div class="learning-clause-list">${(ind.classic_clauses_primary||[]).slice(0,6).map(clause).join('')||'<p class="muted">此方尚未接到原文條文。</p>'}</div>${(ind.classic_clauses_caution||[]).length?`<details><summary>禁例／非適用條文</summary>${(ind.classic_clauses_caution||[]).slice(0,5).map(clause).join('')}</details>`:''}</section>`;
    }
    variantLine(v){const name=v.variant_display_name||v.variant_formula_name||v.target_formula_name||'未命名變方';const delta=this.variantDeltaText(v);const src=v.variant_display_source||v.source_book||'';const tid=v.variant_formula_id||v.target_formula_id||'';return `<li><b>${esc(name)}</b><span class="chip">${esc(v.variant_display_relation||'加減／變方')}</span><div>${esc(delta)}</div>${src?`<div class="muted">來源：${esc(src)}</div>`:''}${tid?`<button class="btn mini" data-open-entity="${esc(tid)}">開節點</button>`:''}</li>`;}
    renderFormula(){const f=this.selectedFormula();this.body().innerHTML=`<div class="learning-detail-shell"><aside class="card learning-type-list"><h3>方劑</h3><input id="learnFormulaSearch" placeholder="搜尋：桂枝湯、小柴胡湯、五苓散"><div id="learnFormulaList"></div></aside><main class="card learning-type-detail"><div class="learning-detail-head"><div><h3>${esc(f.name||'方劑')}</h3><p class="muted mono">${esc(f.formula_id||'')}</p></div><button class="btn" data-open-entity="${esc(f.formula_id||'')}">開節點</button></div><h4>必背組成</h4><p class="big-line">${esc(f.composition||'待核對')}</p>${f.component_preview_by_book?`<p class="muted">依書籍核對：${esc(f.component_preview_by_book)}</p>`:''}${this.renderFormulaIndications(f.indications)}<h4>學習策略</h4><ul>${(f.why_learn||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>加減／變方</h4>${(f.variants||[]).length?`<ul class="variant-learning-list">${f.variants.map(v=>this.variantLine(v)).join('')}</ul>`:'<p class="muted">目前未建立變方資料或待核對。</p>'}<h4>正式題樣本</h4><div class="learning-example-list">${(f.examples||[]).map(q=>this.qCard(q)).join('')||'<p class="muted">沒有樣本。</p>'}</div><h4>主動回憶</h4>${(f.recall_cards||[]).map(c=>`<div class="card soft"><b>${esc(c.prompt)}</b><details><summary>顯示答案</summary><p>${esc(c.answer)}</p></details><button class="btn" data-add-recall="${esc(f.formula_id)}" data-kind="formula">加入回憶清單</button></div>`).join('')}</main></div>`;this.renderFormulaList();}
    pdCards(){return this.p.pattern_disease_cards||[]}
    selectedPD(){return this.pdCards().find(x=>x.entity_id===this.pd)||this.pdCards()[0]||{}}
    renderPdList(q=''){const host=this.root.querySelector('#learnPdList');if(!host)return;q=String(q||'').trim();const rows=this.pdCards().filter(x=>!q||String(x.name).includes(q)||String(x.entity_id).includes(q)).slice(0,120);host.innerHTML=rows.map(x=>`<button class="type-list-row ${x.entity_id===this.pd?'active':''}" data-learn-pd="${esc(x.entity_id)}"><b>${esc(x.name)}</b><span>${esc(typeLabel[x.type]||x.type)}｜${esc(x.question_count||0)}</span></button>`).join('')||'<p class="muted">找不到病證／證型。</p>'}
    renderPD(){const d=this.selectedPD();this.body().innerHTML=`<div class="learning-detail-shell"><aside class="card learning-type-list"><h3>病證／證型</h3><input id="learnPdSearch" placeholder="搜尋：痰熱、太陽中風、咳嗽"><div id="learnPdList"></div></aside><main class="card learning-type-detail"><div class="learning-detail-head"><div><h3>${esc(d.name||'病證／證型')}</h3><p class="muted">${esc(typeLabel[d.type]||d.type||'')}｜正式題樣本 ${esc(d.question_count||0)} 題</p></div><button class="btn" data-open-entity="${esc(d.entity_id||'')}">開節點</button></div><h4>主症／線索候選</h4><div class="chip-list">${(d.feature_hints||[]).map(x=>`<span class="chip">${esc(x.name)} ${esc(x.count)}</span>`).join('')||'<span class="muted">待由題目與原文補強。</span>'}</div><h4>學習策略</h4><ul>${(d.learning_focus||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>正式題樣本</h4><div class="learning-example-list">${(d.examples||[]).map(q=>this.qCard(q)).join('')}</div><button class="btn" data-add-recall="${esc(d.entity_id)}" data-kind="pattern">加入回憶清單</button></main></div>`;this.renderPdList();}
    renderChapter(){
      const rows=this.p.chapter_paths||[];
      const sectionItem=s=>`<li class="chapter-path-item"><b>${esc(s.title)}</b> <span class="muted">${esc(s.level||'')}</span>${s.study_note?`<div class="muted">${esc(s.study_note)}</div>`:''}<div class="chapter-actions"><button class="btn mini" data-run-search="${esc(s.title)}">查此綱目</button><button class="btn mini primary" data-quiz-scope='${esc(JSON.stringify({section_id:s.section_id,book_id:s.book_id||'',tree_label:s.title,keywords:[s.title],layer:'official_exam'}))}'>以此綱目出題</button></div></li>`;
      this.body().innerHTML=`<div class="card"><h3>v5.3：章節綱目導向學習路徑</h3><p>每本書預設展開。章節按鈕可查詢節點資料，也可直接把該綱目與下層關鍵字送入出題系統；不取代原資料頁。</p><div class="learning-book-compact">${rows.map(b=>`<button class="legend-row compact" data-quiz-scope='${esc(JSON.stringify({learning_book_id:b.book_id,tree_label:b.label,keywords:[b.label],layer:'official_exam'}))}'><b>${esc(b.label)}</b><span>${esc(b.section_count)} 綱目</span></button>`).join('')}</div><div class="grid learning-mini-stats chapter-grid">${rows.map(b=>`<div class="card soft"><h4>${esc(b.label)}</h4><p>${esc(b.section_count)} 個綱目／節點</p>${b.study_path_note?`<p class="muted">${esc(b.study_path_note)}</p>`:''}<button class="btn primary" data-quiz-scope='${esc(JSON.stringify({learning_book_id:b.book_id,tree_label:b.label,keywords:[b.label],layer:'official_exam'}))}'>以本書出題</button><details open><summary>綱目入口</summary><ol>${(b.top_sections||[]).slice(0,80).map(sectionItem).join('')}</ol></details></div>`).join('')}</div></div>`
    }
    compareIndex(){return this.p.comparison_index||{nodes:[],neighbor_map:{},question_map:{}}}
    cmpNode(id){return (this.compareIndex().nodes||[]).find(n=>n.id===id)||null}
    cmpMatches(q){q=String(q||'').trim();const nodes=this.compareIndex().nodes||[];let rows=nodes.filter(n=>!q||String(n.name).includes(q)||String(n.id).includes(q)); rows.sort((a,b)=>(Number(b.question_count||0)-Number(a.question_count||0))); return rows.slice(0,80);}
    renderCompareList(side,q=''){const host=this.root.querySelector(side==='b'?'#cmpListB':'#cmpListA');if(!host)return;const cur=side==='b'?this.cmpB:this.cmpA;const rows=this.cmpMatches(q);host.innerHTML=rows.map(n=>`<button class="type-list-row ${n.id===cur?'active':''}" data-compare-side="${side}" data-compare-pick="${esc(n.id)}"><b>${esc(n.name)}</b><span>${esc(typeLabel[n.type]||n.type)}｜${esc(n.question_count||0)}</span></button>`).join('')||'<p class="muted">找不到節點。</p>';}
    renderCompare(){const ci=this.compareIndex();const A=this.cmpNode(this.cmpA),B=this.cmpNode(this.cmpB);if(!A||!B){this.body().innerHTML='<div class="card">鑑別索引尚未就緒。</div>';return;}const na=ci.neighbor_map?.[A.id]||[], nb=ci.neighbor_map?.[B.id]||[];const mapA=new Map(na.map(x=>[x.id,x])), mapB=new Map(nb.map(x=>[x.id,x]));const common=na.filter(x=>mapB.has(x.id)).slice(0,30);const uniqA=na.filter(x=>!mapB.has(x.id)).slice(0,30);const uniqB=nb.filter(x=>!mapA.has(x.id)).slice(0,30);const qa=ci.question_map?.[A.id]||{}, qb=ci.question_map?.[B.id]||{};const qsetB=new Set(qb.qids||[]);const shared=(qa.qids||[]).filter(x=>qsetB.has(x));this.body().innerHTML=`<div class="learning-compare-shell"><aside class="card learning-type-list"><h3>A 節點</h3><input id="cmpSearchA" placeholder="搜尋方劑、症狀、證型、藥物"><div id="cmpListA"></div></aside><main class="card learning-compare-main"><h3>任兩節點鑑別：${esc(A.name)} vs ${esc(B.name)}</h3><p class="muted">用途：把兩個容易混淆或想建立關係的節點，拆成「共同骨架、A 獨有、B 獨有、共同考題」。自動整理屬 D 級候選；正式背誦前仍需回到原文、正式題與方劑頁考證。</p><div class="compare-two-head"><div><b>${esc(A.name)}</b><span class="badge">${esc(typeLabel[A.type]||A.type)}</span><span class="chip">正式題 ${esc(qa.official_count||A.question_count||0)}</span><button class="btn mini" data-open-entity="${esc(A.id)}">開節點</button></div><div><b>${esc(B.name)}</b><span class="badge">${esc(typeLabel[B.type]||B.type)}</span><span class="chip">正式題 ${esc(qb.official_count||B.question_count||0)}</span><button class="btn mini" data-open-entity="${esc(B.id)}">開節點</button></div></div><section class="compare-block helpful"><h4>對考生有什麼幫助</h4><ul><li>同類節點：用來抓考場分歧點，例如「哪個症狀或藥物只屬於其中一方」。</li><li>不同類節點：用來看上下游關係，例如「症狀支持哪些證型，證型連到哪些方劑」。</li><li>共同考題：用來找出兩者會一起出現或容易互相干擾的考法。</li></ul></section><div class="compare-grid"><section class="compare-block"><h4>共同關聯</h4>${this.relList(common,'common')}</section><section class="compare-block"><h4>${esc(A.name)} 獨有關聯</h4>${this.relList(uniqA,'a')}</section><section class="compare-block"><h4>${esc(B.name)} 獨有關聯</h4>${this.relList(uniqB,'b')}</section></div><section class="compare-block"><h4>共同正式題</h4><p>${shared.length} 題同時連到兩節點。若數量高，表示這組鑑別值得練。</p><div class="learning-example-list">${(qa.examples||[]).concat(qb.examples||[]).slice(0,6).map(q=>this.qCard(q)).join('')||'<p class="muted">沒有樣本。</p>'}</div></section></main><aside class="card learning-type-list"><h3>B 節點</h3><input id="cmpSearchB" placeholder="搜尋：麻黃湯、豬苓湯、口渴"><div id="cmpListB"></div></aside></div>`;this.renderCompareList('a');this.renderCompareList('b');}
    relList(arr,cls){if(!arr.length)return '<p class="muted">目前未找到穩定關聯。</p>';return `<div class="compare-rel-list ${cls}">${arr.map(x=>`<div class="compare-rel"><b>${esc(x.name)}</b><span class="badge">${esc(typeLabel[x.type]||x.type)}</span><div class="muted">${(x.relations||[]).slice(0,3).map(r=>esc(relLabel[r]||r)).join('、')}｜關聯 ${esc(x.count||1)}</div>${(x.evidence||[]).length?`<div class="tiny-evidence">${esc(x.evidence[0])}</div>`:''}<button class="btn mini" data-open-entity="${esc(x.id)}">開節點</button></div>`).join('')}</div>`}
    renderRecallHidden(){this.body().innerHTML=`<div class="card"><h3>v5.4 主動回憶與錯題回流：暫時隱藏</h3><p>目前本機回憶清單仍屬 MVP，尚未與錯題本、雲端同步與節點學習卡完整整合。為避免半成品干擾考生，本功能先不放主流程；待功能完成後再正式放入主流程。</p><p class="muted">既有錯題本仍在考題系統中可用，不受影響。</p></div>`}
    renderRecall(){this.loadRecall();this.body().innerHTML=`<div class="card"><h3>v5.4：主動回憶與錯題回流 MVP</h3><p>目前先做本機回憶清單，不覆蓋既有錯題本。之後可把答錯題目自動回流到對應方劑／證型卡。</p><div class="toolbar"><button class="btn" data-add-recall="${esc(this.formula||'')}" data-kind="formula">加入目前方劑</button><button class="btn" data-add-recall="${esc(this.pd||'')}" data-kind="pattern">加入目前病證／證型</button></div><div>${this.recall.length?this.recall.map((r,i)=>`<div class="card soft"><b>${esc(r.name||r.id)}</b><span class="badge">${esc(r.kind)}</span><p class="muted">加入：${esc(r.at||'')}</p><button class="btn primary" data-recall-done="${i}">已會</button><button class="btn" data-recall-miss="${i}">不會，保留</button></div>`).join(''):'<p class="muted">尚無回憶卡。可在方劑卡或病證／證型卡加入。</p>'}</div></div>`}
    addRecall(id,kind){if(!id)return;let name=id;if(kind==='formula'){const f=this.formulaCards().find(x=>x.formula_id===id);if(f)name=f.name}else{const d=this.pdCards().find(x=>x.entity_id===id);if(d)name=d.name}this.recall.push({id,kind,name,at:new Date().toLocaleString(),status:'new'});this.saveRecall();this.mode='recall';this.render();}
    markRecall(idx,done){idx=Number(idx);if(done)this.recall.splice(idx,1);else if(this.recall[idx]){this.recall[idx].status='miss';this.recall[idx].at=new Date().toLocaleString()}this.saveRecall();this.renderRecall();}
    qCard(q){return `<article class="learning-example"><div class="example-meta"><b>${esc(q.period)} ${esc(q.subject||'')} #${esc(q.question_no||q.no||'')}</b><span class="badge">正式題 A</span></div><p>${esc(short(q.stem,220))}</p><div class="muted">正解：${esc(q.answer_label||q.answer||'')} ${esc(q.answer_text||'')}</div><div class="example-actions"><button class="btn primary" data-open-question="${esc(q.question_id||q.id||'')}">開題目</button></div></article>`}
  }
  async function mount(root,opts={}){root=typeof root==='string'?document.querySelector(root):root;if(!root)return null;root.innerHTML='<div class="spinner">載入學習頁…</div>';const url=opts.payloadUrl||'data/learning_exam_pattern_payload_v5_0a.json';const r=await fetch(url);if(!r.ok)throw new Error('無法載入 '+url+'：HTTP '+r.status);const payload=await r.json();const inst=new LearningPage(root,payload);global.Clinical1LearningInstance=inst;inst.render();return inst;}
  global.Clinical1LearningPage={mount,LearningPage};
})(window);
